
server:
  port: 41000
  context-path: /

logging:
  level:
    root: info
    org.springframework.jdbc: debug
  file: ${spring.application.name}.log
spring:
  application:
    name: magic-tumblr-wechat-intf
  datasource:
    tomcat:
      url: jdbc:h2:~/h2/dbp;FILE_LOCK=SOCKET;SCHEMA=magic_tumblr
      #username: magic
      max-active: 20
      max-idle: 10
      min-idle: 5
      max-wait: 10000
      default-auto-commit: false
      login-timeout: 5
      remove-abandoned: true
      remove-abandoned-timeout: 30
      test-while-idle: true
      test-on-borrow: true
      validation-query: select 1
      log-abandoned: true
      log-validation-errors: true
      driver-class-name: org.h2.Driver
    username: magic
wechat:
  appId: xxxx
  appSecret: zzzz


i18n:
  message:
    urlReceived: 魔法工厂正在解析URL....\n友情提醒：发送Q+%s可查询进度。
    sysError: 非常抱歉，系统正在开小差，过会再试试吧。

  exception:
    e0001: asdfasdfa
    e0002: 好气呀 -_-|| 魔法汤工厂暂时不可用。