
server:
  port: 41000
  context-path: /

logging:
  level:
    root: info
    #org.springframework.jdbc: debug
  file: ${spring.application.name}.log
spring:
  application:
    name: magic-tumblr-wechat-intf
  datasource:
    tomcat:
      url: jdbc:h2:~/h2/dbp;FILE_LOCK=SOCKET;SCHEMA=magic_tumblr
      max-active: 20
      max-idle: 10
      min-idle: 5
      max-wait: 10000
      default-auto-commit: false
      login-timeout: 5
      remove-abandoned: true
      remove-abandoned-timeout: 30
      test-while-idle: true
      test-on-borrow: true
      validation-query: select 1
      log-abandoned: true
      log-validation-errors: true
      driver-class-name: org.h2.Driver
    username: magic
wechat:
  appId: xxxx
  appSecret: zzzz


i18n:
  message:
    contentReceived: YOHOO！请求已收到，魔法汤儿正在努力解析中，稍等片刻。\\n过那么一小会会儿，回复Q(q)查询结果哟。
    urlReceived: 魔法汤婆婆正在解析URL....\n友情提醒：发送Q+%s可查询进度。
    sysError: 非常抱歉，系统正在开小差，过会再试试吧。
    noAssetFound: 魔法汤找了半天，仍然一无所获。I am so sad!
    videoCodeFound: 哈哈哈！施主请「笑纳」。\n解析结果为：https://vt.tumblr.com/tumblr_%s.mp4
    urlParseFailed: 哟～哟～哟～，解析失败了。
    underProcess: 还在解析哟，施主稍等片刻再查，好么？
    unsupportedUrl: 魔法汤暂不支持解析此URL[%s]
    waitForParse: 正在排队解析，骚等，少年。
    dizzy: 说真的，我也不知道怎么回事，数据好像有点不正常。有些事不能做，有些话不能说，做人挺难的。
    queryEmpty: 其实我不想说你什么都没查到。发送"帮助"或者"help"，GET使用魔法汤的正确姿势。
    assetFound: 魔法老师准备划重点了，做好笔记，老铁\\n%s
    assetResultTemplate: 时间：%s\\n内容：%s\\n结果：%s
    assetSurprise: 惊喜：%s
  exception:
    e0001: 啊喔!?! 魔法汤四目紧盯指令[%s]，紧锁的眉头间蹦出仨字「什么鬼」。
    e0002: 好气呀 -_-|| 魔法汤工厂暂时不可用。